CREATE TABLE Cards
(
	Id INT IDENTITY(1,1) NOT NULL,
	Number VARCHAR(19) NOT NULL,
	Balance DECIMAL(18,2) DEFAULT(0.00) CHECK(Balance >= 0.00) NULL,
	Pincode VARCHAR(4) NOT NULL,
	CVV VARCHAR(3) NOT NULL,
	[User_Id] INT NOT NULL,
	PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT FK_Cards_To_Users FOREIGN KEY([User_Id]) REFERENCES Users(Id) ON DELETE CASCADE,
	CONSTRAINT UQ_Number UNIQUE(Number)
);
